In [1]:
import numpy as np

# Q: Given a 6x6 NumPy array r, which of the following options would slice the shaded elements?

<img src="https://d3c33hcgiwev3.cloudfront.net/imageAssetProxy.v1/ld68zYqoEeaCXQ5dBCgoUw_5c8cf678f7cb43d00e2b9e30c434b0c6_Slice1.png?expiry=1500768000000&hmac=BYwR-6lvgTOkAUhnmPkVtFG9ld1E-m19KN8u8tbQpNk"/> 

In [9]:
r = np.random.randint(10,size=(6,6))
print(r)

[[9 0 7 9 4 6]
 [5 3 1 8 5 0]
 [4 5 3 4 0 1]
 [0 3 1 2 3 5]
 [2 3 1 7 3 4]
 [9 3 0 3 1 9]]


In [11]:
r.reshape(36)[::7] # Correct

array([9, 3, 3, 2, 3, 9])

# Q: Given a 6x6 NumPy array r, which of the following options would slice the shaded elements?

<img src="https://d3c33hcgiwev3.cloudfront.net/imageAssetProxy.v1/INF_bIqrEealuRI3K47d-Q_0931f86653a0cee389ee5b03480acb7d_Slice3.png?expiry=1500768000000&hmac=OCai8t6JHyXunk5Txd3qSNCgKy3qpT_p1-Flm6AwbYE" />

In [15]:
r[2:4,2:4] # Correct

array([[3, 4],
       [1, 2]])